    - name: vmdesc 
      debug: 
        msg: "{{ vmdesc }}"
    #- meta: end_play
    
    - name: creating data volumes
      os_volume:
        state: present
        size: "{{ vmdesc.sizeGB }}"
        display_name: "{{ item }}"
      with_sequence: start=1 end={{vmdesc.number}} format={{vmdesc.prefix}}%04x
      loop_control:
       pause: 3
           
    - name: Create a new VM instance
      os_server:
        state: present
        name: "{{ vmdesc.vmname }}"
        image: "{{ pvc_image_name }}"
        flavor: "{{ pvc_flavor }}"
        key_name: tower-ansible-ssh-key
        nics:
          - net-name: VL354-115-119
        meta:
          hostname: "{{ vmdesc.vmname }}"
          group: ansible-vms
      register: vm

    - name: set hostip with  VM's public IP address
      set_fact:
        hostip: "{{vm.openstack.public_v4}}"
    - name: Adding ip address to list
      set_fact:
        ip_adresses: "{{ ip_adresses }} + [ '{{ hostip}}' ]"  
    - name: Add host just_created to just_added group
      add_host:
        name: "{{vm.openstack.public_v4}}"
        group: just_added
    - name: attach volume to host
      os_server_volume:
        state: present
        server: "{{vmdesc.vmname}}"
        volume: "{{ item }}"
      with_sequence: start=1 end={{vmdesc.number}} format={{vmdesc.prefix}}%04x

