---
- hosts: all
  become: yes
  gather_facts: no
  vars_files:
    - vars/oracle-vars.yml
  tasks:
    - name: checking free space in /var
      shell: "df -g /var | tail -1  |awk '{print $2}'"
      register : freevar
    - name: free space checkkkk
      assert: 
        that: "{{freevar.stdout}}  > 0.25"
        msg: more that 250M Free
      vars: 
        extendvar: true
    - name: extending /var of 250M
      shell : "chfs -a size=+250M /var"
      when : "{{extendvar}} == true"
    - meta: end_play
    - name: setiing var
      set_fact:
        attr: "{{iocp0.stdout_lines[1]}}"
    - name: generating system reboot script
      copy:
        src: roles/aix/files/rebootscript.sh
        dest: /tmp/rebootscript.sh
        mode: '0770'
      when: attr  == "defined"
    #- meta: end_play
    - name: executing system reboot script
      shell : "/tmp/rebootscript.sh"
      when: attr  == "defined"
      #when: {{iocp0.stdout_lines[1]}} == "defined"
    - name: Wait 600 seconds, but only start checking after 120 seconds
      wait_for_connection:
        delay: 120
        timeout: 600
        sleep: 20
        connect_timeout: 10
      when: attr  == "defined"
      #when: {{iocp0.stdout_lines[1]}} == "defined"
