- name: Create a PowerVC Virtual Machine
  hosts: localhost
  vars_files:
    # User defined variables for infrastructure
    - vars/osvars.yml
  vars_prompt:
    - name: username
      prompt: "What is your username?"
      private: no
  
  tasks:
  # Creates a new volume
  - name: create 40g test volume
    os_volume:
      state: present
      #cloud: mordred
      size: 40
      display_name: "{{ username }}"
    register: disk
  - name : debug
    debug: 
      msg : "{{disk}}"
  - name: attach volume to host
    os_server_volume:
      state: present
      server: ansible7
      volume: "{{ username }}"
      #device: /dev/vdb

  - debug:
        msg: 'Logging in as {{ username }}' 
