---
- hosts: localhost
  environment:
  #script to run as source powervcrc to be able to run nova command ##
    OS_USERNAME: root
    OS_PASSWORD: powerlinux
    OS_AUTH_URL: https://10.3.44.10:5000/v3/
    OS_IDENTITY_API_VERSION: 3 
    OS_CACERT: /var/lib/awx/projects/pvc_ansible/ossia/powervc.crt
    OS_REGION_NAME: RegionOne
    OS_USER_DOMAIN_NAME: Default 
    OS_PROJECT_DOMAIN_NAME: Default
    OS_PROJECT_NAME: Ansible
    OS_TENANT_NAME: ibm-default
  gather_facts: yes
  vars_files:
    - vars/osvars.yml
  roles:
      - pvc
      
   
#- hosts: 10.3.54.119
  #become: yes
  #become_user: root
  #vars_files:
    #- vars/osvars.yml
  #gather_facts: yes
  #roles: 
    #- r2
