- name: remove an instance
  environment:
    OS_USERNAME: root
    OS_PASSWORD: powerlinux
    OS_AUTH_URL: https://10.3.44.10:5000/v3/
    OS_IDENTITY_API_VERSION: 3
    OS_CACERT: /var/lib/awx/projects/pvc_ansible/ossia/powervc.crt
    OS_REGION_NAME: RegionOne
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_DOMAIN_NAME: Default
    OS_PROJECT_NAME: Ansible
    OS_TENANT_NAME: ibm-default
  hosts: localhost
  vars_files:
    # User defined variables for infrastructure
    - vars/osvars.yml
  tasks:
    - name: remove an instance
      os_server:
        name: "{{ item.vmname }}"
        state: absent
        terminate_volume: yes
      loop : "{{ hostnames }}"
    - name: delete 40g test volume
      os_volume:
        state: absent
        display_name: "{{ item }}"
      with_sequence: start=1 end={{disk_list.number}} format={{disk_list.prefix}}%04x
      #
