---
- hosts: all
  remote_user: root
  vars_files:
  gather_facts: yes
  roles:
    - sshX11
  #tasks:
    #- name: accessing value 
      #shell: hostname
      #register: sn
    #- debug:
        #msg : "{{sn}}"
      #  msg: "{{hostvars['localhost']['h1var']}}"

        #msg:  "{{h1var}}"

